/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  AuthToken,
} from './interface';

export namespace Components {
  interface ManifoldOauth {
    'tick'?: string;
  }
}

declare global {


  interface HTMLManifoldOauthElement extends Components.ManifoldOauth, HTMLStencilElement {}
  var HTMLManifoldOauthElement: {
    prototype: HTMLManifoldOauthElement;
    new (): HTMLManifoldOauthElement;
  };
  interface HTMLElementTagNameMap {
    'manifold-oauth': HTMLManifoldOauthElement;
  }
}

declare namespace LocalJSX {
  interface ManifoldOauth extends JSXBase.HTMLAttributes<HTMLManifoldOauthElement> {
    'onReceiveManifoldToken'?: (event: CustomEvent<AuthToken>) => void;
    'tick'?: string;
  }

  interface IntrinsicElements {
    'manifold-oauth': ManifoldOauth;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


